version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data.sqlite:/app/data.sqlite
    expose:
      - "5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
